### ISSUE TITLE
ERROR: spawn pdftocairo ENOENT

### ISSUE THREAD

**Issue by IsmaHub** [rreusser/gulp-pdftocairo#2]
I try to convert a pdf file to png format but produces this error:

```
"message":"spawn pdftocairo ENOENT"
"Error: spawn pdftocairo ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:182:32
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)"
```
## gulpfile.js

notice: I'm call the task named _toPdfChangeTasks_ for this objective.

``` javascript
var gulp            = require('gulp');
var ext_replace     = require('gulp-ext-replace');
var del             = require('del');
var pdftocairo      = require('gulp-pdftocairo')

 gulp.task('pdftopng', 
            ()=> {
                gulp.src('origin/*.pdf')
                    .pipe(pdftocairo({format: 'png', resolution: 800}) )
                    .pipe(gulp.dest('origin') );
            });

gulp.task('change', ()=> {
        gulp.src('origin/*.*')
            .pipe(ext_replace('.jpg') )
            .pipe(gulp.dest('thumbs') );
});


gulp.task('clean:origin', 
            ()=> {
                    return del([
                                './origin/**/*',
                                // we don't want to clean this file though so we negate the pattern
                                //'!./origin/prueba.pdf'
                            ]);
            });

gulp.task('toPdfChangeTasks', ['pdftopng', 'change', 'clean:origin']);
gulp.task('changeTasks', ['change', 'clean:origin']);
```

**Comment by rreusser** [comment]
Hmm… first things first, is pdftocairo installed and available in your `PATH`? Does `pdftocairo` work from the command line? That's what it _looks_ like it's saying, but there's a chance it's talking about the files themselves. It's not quite clear to me. Your gulpfile looks nearly identical to the [use-case](https://github.com/rreusser/mdtex-cli/blob/master/index.js#L52) I was using this for, so a usage issue doesn't immediately jump out.

I wouldn't think you'd need to, but depending on your setup, you could try being really specific and [passing the full path of pdftocairo as `command`](https://github.com/rreusser/gulp-pdftocairo#requiregulp-pdftocairo-options-) to ensure that it's finding it.
